config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'
  delete '/apppointment/:id' => 'appointments#destroy'
  delete '/patient/:id' => 'patients#destroy'
  delete '/note/:id' => 'notes#destroy'

#omniauth callback route
  get '/auth/:provider/callback' => 'sessions#google'

  resources :users do
    resources :patients, :appointments, shallow: true
  end
  resources :patients do
    resources :notes, :appointments
  end
  resources :appointments
  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :patient

  validates :date, presence: true
  validates :time, presence: true

  def self.from_today
    where('date ==?', Date.today)
  end

  def self.future_appointments
    where('date > ?', Date.today)
  end

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :patient

  validates :content, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_many :notes

  validates :name, presence: true
  validates :birthdate, presence: true
  validates :sex, presence: true

  scope :alpha, -> { order (:name) }

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password #authenticate, validate password and/or password confirmation

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
  has_many :notes


  validates :name, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :nested_user #to be accessible in the views

  private

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    User.find_by_id(session[:user_id])
  end

  def redirect_if_not_logged_in
    redirect_to '/' if !logged_in?
  end

  def nested_user
    params[:user_id]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_appointment_user, only: [:edit, :update, :destroy]

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @appointments = @user.appointments
    else
      @appointments = Appointment.all
    end
    if !params[:date].blank?
      if params[:date] == "Today"
        @appointments = @user.appointments.from_today
      else
        @appointments = @user.appointments.future_appointments
      end
    end
  end

  def new
    if params[:patient_id] && @patient = Patient.find_by_id(params[:patient_id])
      @appointment = @patient.appointments.build
    else
      @appointment = Appointment.new
    end
  end

  def create
    @patient = Patient.find_by_id(params[:patient_id])
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      redirect_to appointments_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointment_path(@appointment)
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path(@user)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :time, :patient_id)
  end

  def set_appointment
    @appointment = Appointment.find_by_id(params[:id])
    if !@appointment
      flash[:message] = "Appointment was not found"
      redirect_to appointments_path
    end
  end

  def redirect_if_not_appointment_user
    if @appointment.user != current_user
      redirect_to appointments_path
      flash[:message] = "***You cannot delete an appointment that is not yours.***"
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_note_author, only: [:edit, :update, :destroy]

  def index
    if params[:patient_id] && @patient = Patient.find_by_id(params[:patient_id])
      @notes = @patient.notes
    else
      @notes = Note.all
    end
  end

  def new
    if params[:patient_id] && @patient = Patient.find_by_id(params[:patient_id])
      @note = @patient.notes.build
    else
      @note = Note.new
    end
  end

  def create
    @patient = Patient.find_by_id(params[:patient_id])
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to patient_path(@note.patient_id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to note_path
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path(@note)
  end

  private

  def note_params
    params.require(:note).permit(:content, :patient_id)
  end

  def set_note
    @note = Note.find_by_id(params[:id])
    if !@note
      redirect_to notes_path
    end
  end

  def redirect_if_not_note_author
    if @note.user != current_user
      redirect_to notes_path
      flash[:message] = "***You cannot delete a note that is not yours.***"
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @patients = @user.patients.alpha.uniq
    else
      @patients = Patient.alpha
    end
     if params[:search]
       @patients = Patient.search(params[:search])
     end
  end

  def new
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @patient = @user.patients.build
    else
      @patient = Patient.new
    end
  end

  def create
    @patient = current_user.patients.build(patient_params)
    if @patient.save
      redirect_to patient_path(@patient)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :birthdate, :sex)
  end

  def set_patient
    @patient = Patient.find_by_id(params[:id])
    if !@patient
      redirect_to patients_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def home
  end

  def create
    user =  User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid username or password. Please try again."
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def google
    @user = User.find_or_create_by(username: auth["info"]["email"]) do |user|
      user.name = auth["info"]["name"]
      user.password = SecureRandom.hex(15)
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  private

  def auth #method to request the auth hash
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, Patient.all.collect { |p| [p.name, p.id] } %>
  <br />
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br />
  <%= f.label :time %>
  <%= f.time_select :time %>
  <br />
  <br />
  <%= f.submit %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment:</h1>
<br>

<%= render partial: "layouts/errors", locals: {object: @appointment} %>
<!-- render the errors partial, send it the @appointment as the 'object' -->

<%= render 'form' %>

app/views/appointments/index.html.erb
<h1>All Appointments:</h1>

<% if nested_user %>
  <div>
    <h3>Filter Appointments:</h3>
    <%= form_tag(user_appointments_path(@user), method: "get") do %>
      <%= select_tag "date", options_for_select(["Today", "Future Appointments"]), include_blank: true %>
      <%= submit_tag "Filter" %>
    <% end %>
  <br>
    <br>
  </div>
  <% else %>
<% end %>

<% @appointments.each do |a| %>
  <li><%= link_to a.date.strftime("%B %d, %Y"), appointment_path(a) %>, <%= a.time.strftime("%k:%M") %> - <%= a.patient.name %> - w/ Dr. <%= a.user.name %></li>
<% end %>

app/views/appointments/new.html.erb
<h1>Schedule an Appointment:</h1>
<br>

<%= render partial: "layouts/errors", locals: {object: @appointment} %>
<!-- render the errors partial, send it the @appointment as the 'object' -->

<%= render 'form' %>

app/views/appointments/show.html.erb
<h1>Appointment Details:</h1>

<p><b>Patient Name:</b> <%= link_to @appointment.patient.name, patient_path(@appointment.patient) %></p>
<p><b>Doctor Name:</b> Dr. <%= @appointment.user.name %></p>
<p><b>Date:</b> <%= @appointment.date.strftime("%B %d, %Y") %></p>
<p><b>Time:</b> <%= @appointment.time.strftime("%k:%M") %></p>


<%= button_to 'Edit Appointment', edit_appointment_path(@appointment), method: :get %>
<%= button_to 'Delete Appointment', appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthCareNetworkPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if logged_in? %>
        <%= link_to "Home", user_path(current_user)%> |
        <%= link_to "Add a Patient", new_user_patient_path(current_user) %> |
        <%= link_to "View All Patients", patients_path %> |
        <%= link_to "View My Patients", user_patients_path(current_user) %> |
        <%= link_to "View All Appointments", appointments_path %> |
        <%= link_to "View My Appointments", user_appointments_path(current_user) %> |
        <%= link_to "Schedule New Appointment", new_user_appointment_path(current_user) %> |
        <%= link_to "Logout", logout_path, method:"delete"%>
      <% else %>
        <%=link_to "Sign Up", signup_path %> |
        <%=link_to "Log In", login_path %> |
        <%=link_to "Log In With Google", '/auth/google_oauth2' %>
      <% end %>
    </div>

    <div>
      <% if flash[:message] %>
      <br><br>
        <%= flash[:message]%>
      <% end %>
      <%= @error%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <%= f.label :note %>
  <br>
    <br>
  <%= f.text_area :content %>
  <br>
    <br>
    <%= f.hidden_field :patient_id %>
  <%= f.submit 'Post Note' %>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= render partial: "layouts/errors", locals: {object: @note} %>
<!-- render the errors partial, send it the @note as the 'object' -->
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>All Notes:</h1>

<% @notes.each do |n| %>
  <li><%= n.content %> <%= link_to "Click for details", patient_note_path(n.patient_id, n.id) %></li>
<% end %>

<p><%= link_to 'Add New Note', new_patient_note_path(@patient)%></p>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render partial: "layouts/errors", locals: {object: @note} %>
<!-- render the errors partial, send it the @note as the 'object' -->
<%= render 'form' %>

app/views/notes/show.html.erb
<b>Note:</b> <%= @note.content %></p>
<p><b>Noted By:</b> Dr. <%= @note.user.name %></p>

<%= button_to 'Edit Note', edit_note_path(@note), method: :get %>
<%= button_to 'Delete Note', note_path(@note), method: :delete, data: { confirm: "Are you sure you want to delete this note?" } %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %>
  <br>
    <br>
  <%= f.label "Birthdate:" %>
  <%= f.date_field :birthdate %>
  <br>
    <br>
  <%= f.label "Sex:" %>
  <%= f.select(:sex, [ 'Male', 'Female' ], {}, { :class => 'select' }) %>
  <br>
    <br>
  <%= f.submit %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient:</h1>

<%= render partial: "layouts/errors", locals: {object: @patient} %>
<!-- render the errors partial, send it the @patient as the 'object' -->

<%= render 'form' %>

app/views/patients/index.html.erb
<h1>All Patients:</h1>

<% if !nested_user %>
  <%= form_tag(patients_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Patients" %>
  <%= submit_tag "Search" %>
  <% end %>
  <% else %>
<% end %>
<br>
<% @patients.each do |p| %>
  <li><%= link_to p.name, patient_path(p) %></li>
<% end %>

app/views/patients/new.html.erb
<h1>Create a New Patient:</h1>

<%= render partial: "layouts/errors", locals: {object: @patient} %>
<!-- render the errors partial, send it the @patient as the 'object' -->

<%= render 'form' %>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1>
  <p><b>Birthdate:</b> <%= @patient.birthdate.strftime("%B %d, %Y") %></p>
  <p><b>Sex:</b> <%= @patient.sex %></p>

  <%= link_to 'Edit Patient Information', edit_patient_path(@patient)%> |
  <%= link_to 'Delete Patient', patient_path(@patient), method: :delete, data: { confirm: "Are you sure you want to delete this patient?" } %>

<div>
  <h4>Appointments:</h4>
  <% @patient.appointments.each do |a| %>
    <li><%= link_to a.date.strftime("%B %d, %Y"), appointment_path(a) %>, <%= a.time.strftime("%k:%M") %> w/ Dr. <%= a.user.name %></li>
  <% end %>
  <br>
  <%= link_to "Schedule Appointment", new_patient_appointment_path(@patient) %>
</div>

<div>
  <h4>Notes:</h4>
    <%= link_to 'Add New Note', new_patient_note_path(@patient)%> |
    <%= link_to 'See All Notes', patient_notes_path(@patient)%>
    <ul>
    <% @patient.notes.each do |n| %>
      <li><%= n.content %> noted by Dr. <%= n.user.name %></li>
    <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>
<!-- render the errors partial, send it the @user as the 'object' -->

<%= form_for(@user, url:'/signup') do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
   <br>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
   <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
   <br>
    <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>

<!-- display today's date and any appointments for today -->